collision_monitor:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "center_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_nav" 
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 0.5
    source_timeout: 5.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop" and "slowdown" action types,
    # and robot footprint for "approach" action type.
    # Footprint could be "polygon" type with dynamically set footprint from footprint_topic
    # or "circle" type with static footprint set by radius. "footprint_topic" parameter
    # to be ignored in circular case.
    polygons: ["PolygonStop", "PolygonSlow"]
    # polygons: ["VelocityPolygonStop"]
    PolygonStop:
      type: "polygon"
      points: [0.25, 0.15, 0.25, -0.15, 0.0, -0.15, 0.0, 0.15]
      action_type: "stop"
      max_points: 3
      visualize: True
      polygon_pub_topic: "polygon_stop"
    PolygonSlow:
      type: "polygon"
      points: [0.35, 0.2, 0.35, -0.2, 0.0, -0.2, 0.0, 0.2]
      action_type: "slowdown"
      max_points: 3
      slowdown_ratio: 0.5
      visualize: True
      polygon_pub_topic: "polygon_slowdown"
    
    # VelocityPolygonStop:
    #   type: "velocity_polygon"
    #   action_type: "stop"
    #   min_points: 6
    #   visualize: True
    #   enabled: True
    #   polygon_pub_topic: "velocity_polygon_stop"
    #   velocity_polygons: ["rotation", "translation_forward", "translation_backward", "stopped"]
    #   holonomic: false
    #   rotation:
    #     points: [0.25, 0.25, -0.25, 0.25, -0.25, -0.25, 0.25, -0.25]
    #     linear_min: -0.05
    #     linear_max: 0.05
    #     theta_min: -0.6
    #     theta_max: 0.6
    #   translation_forward:
    #     points: [0.35, 0.2, -0.25, 0.2, -0.25, -0.2, 0.35, -0.2]
    #     linear_min: 0.0
    #     linear_max: 0.25
    #     theta_min: -0.6
    #     theta_max: 0.6
    #   translation_backward:
    #     points: [0.25, 0.2, -0.35, 0.2, -0.35, -0.2, 0.25, -0.2]
    #     # points: "[[0.2, 0.3], [0.2, -0.3], [-0.35, -0.3], [-0.35, 0.3]]"
    #     linear_min: -0.25
    #     linear_max: 0.0
    #     theta_min: -0.6
    #     theta_max: 0.6
    #   # This is the last polygon to be checked, it should cover the entire range of robot's velocities
    #   # It is used as the stopped polygon when the robot is not moving and as a fallback if the velocity
    #   # is not covered by any of the other sub-polygons
    #   stopped:
    #     points: [0.2, 0.15, -0.2, 0.15, -0.2, -0.15, 0.2, -0.15]
    #     linear_min: -0.25
    #     linear_max: 0.25
    #     theta_min: -0.6
    #     theta_max: 0.6


    observation_sources: ["range_center", "range_left", "range_right","scan"]
    scan:
      type: "scan"
      topic: "scan"
    pointcloud:
      type: "pointcloud"
      topic: "intel_realsense_r200_depth/points"
      min_height: 0.1
      max_height: 0.5
    range_left:
      type: "range"
      topic: "range_left"
    range_center:
      type: "range"
      topic: "range_center"
    range_right:
      type: "range"
      topic: "range_right"
